
const shipmentData = [
    {
        id: 1,
        supplierName: "ABC Transport",
        supplierPan: "ABCDE1234F",
        tripId: "TRIP-001",
        tripDate: "2025-01-10",
        billingTo: "Tata Steel Ltd",
        fromLocation: "Chennai",
        toLocation: "Bangalore",
        loadingDate: "2025-01-09",
        vehicleNumber: "TN09AB1234",
        vehicleTypeTonnage: "Truck - 16T",
        freightAmount: 45000,
        advanceAmount: 20000,
        otherCharges: 1500,
        totalAdvanceAmount: 21500,
        balanceAmount: 23500
    },
    {
        id: 2,
        supplierName: "XYZ Logistics",
        supplierPan: "PQRSX6789L",
        tripId: "TRIP-002",
        tripDate: "2025-01-12",
        billingTo: "Reliance Industries",
        fromLocation: "Hyderabad",
        toLocation: "Pune",
        loadingDate: "2025-01-11",
        vehicleNumber: "TS07CD5678",
        vehicleTypeTonnage: "Trailer - 20T",
        freightAmount: 60000,
        advanceAmount: 30000,
        otherCharges: 2000,
        totalAdvanceAmount: 32000,
        balanceAmount: 28000
    },
    {
        id: 3,
        supplierName: "Rapid Movers",
        supplierPan: "LMNOP4321Q",
        tripId: "TRIP-003",
        tripDate: "2025-01-15",
        billingTo: "Infosys Ltd",
        fromLocation: "Bangalore",
        toLocation: "Chennai",
        loadingDate: "2025-01-14",
        vehicleNumber: "KA05EF9012",
        vehicleTypeTonnage: "Container - 18T",
        freightAmount: 52000,
        advanceAmount: 25000,
        otherCharges: 1800,
        totalAdvanceAmount: 26800,
        balanceAmount: 25200
    },
    {
        id: 4,
        supplierName: "South India Carriers",
        supplierPan: "ASDFG9988K",
        tripId: "TRIP-004",
        tripDate: "2025-01-18",
        billingTo: "ITC Limited",
        fromLocation: "Coimbatore",
        toLocation: "Kochi",
        loadingDate: "2025-01-17",
        vehicleNumber: "TN33GH3456",
        vehicleTypeTonnage: "Truck - 12T",
        freightAmount: 38000,
        advanceAmount: 18000,
        otherCharges: 1200,
        totalAdvanceAmount: 19200,
        balanceAmount: 18800
    },
    {
        id: 5,
        supplierName: "National Freight Services",
        supplierPan: "ZXCVB5566M",
        tripId: "TRIP-005",
        tripDate: "2025-01-20",
        billingTo: "HUL",
        fromLocation: "Mumbai",
        toLocation: "Ahmedabad",
        loadingDate: "2025-01-19",
        vehicleNumber: "MH12JK7890",
        vehicleTypeTonnage: "Trailer - 22T",
        freightAmount: 70000,
        advanceAmount: 35000,
        otherCharges: 2500,
        totalAdvanceAmount: 37500,
        balanceAmount: 32500
    },
    {
        id: 6,
        supplierName: "Fast Track Logistics",
        supplierPan: "QWERT1122Z",
        tripId: "TRIP-006",
        tripDate: "2025-01-22",
        billingTo: "Larsen & Toubro",
        fromLocation: "Pune",
        toLocation: "Nagpur",
        loadingDate: "2025-01-21",
        vehicleNumber: "MH31LM4567",
        vehicleTypeTonnage: "Truck - 14T",
        freightAmount: 42000,
        advanceAmount: 20000,
        otherCharges: 1000,
        totalAdvanceAmount: 21000,
        balanceAmount: 21000
    }
];

export default shipmentData;
